# language: python
# python:
#   - "3.7"
# install: "pip install -r requirement.txt"
# script: coverage run unit_tests.py
# after_success: bash <(curl -s https://codecov.io/bash)


sudo: required
language: python
services:
- docker

script:
- docker image build -t yariski/assignment-2 .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push yariski/assignment-2
  #test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-331194181497"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
